// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package services

import (
	"github.com/mdeheij/tacoservice/tacodb"
)

// Injectors from inject.go:

func Tacofancy() *tacodb.Tacofancy {
	tacofancy := tacodb.NewTacofancy()
	return tacofancy
}
