apiVersion: v1
kind: Service
metadata:
  name: {{ include "tacoservice.fullname" . }}-backend
  annotations:
    prometheus.io/port: "9104"
    prometheus.io/scrape: "true"
  labels:
    {{- include "tacoservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "tacoservice.selectorLabels" . | nindent 4 }}
