{{/*---*/}}
{{/*apiVersion: rbac.authorization.k8s.io/v1*/}}
{{/*kind: ClusterRole*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "tacoservice.serviceAccountName" . }}-cr*/}}
{{/*  labels:*/}}
{{/*  {{- include "tacoservice.labels" . | nindent 4 }}*/}}
{{/*rules:*/}}
{{/*  - apiGroups:*/}}
{{/*      - ''*/}}
{{/*    resources:*/}}
{{/*      - pods*/}}
{{/*      - pods/log*/}}
{{/*      - namespaces*/}}
{{/*      - services*/}}
{{/*    verbs:*/}}
{{/*      - get*/}}
{{/*      - list*/}}
{{/*---*/}}
{{/*apiVersion: rbac.authorization.k8s.io/v1*/}}
{{/*kind: ClusterRoleBinding*/}}
{{/*metadata:*/}}
{{/*  name: {{ include "tacoservice.serviceAccountName" . }}-rb*/}}
{{/*  labels:*/}}
{{/*  {{- include "tacoservice.labels" . | nindent 4 }}*/}}
{{/*roleRef:*/}}
{{/*  kind: ClusterRole*/}}
{{/*  name: {{ include "tacoservice.serviceAccountName" . }}-cr*/}}
{{/*  apiGroup: rbac.authorization.k8s.io*/}}
{{/*subjects:*/}}
{{/*  - kind: ServiceAccount*/}}
{{/*    name: {{ include "tacoservice.serviceAccountName" . }}*/}}
{{/*    namespace: default*/}}
{{/*---*/}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "tacoservice.name" .}}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "tacoservice.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "tacoservice.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "tacoservice.fullname" . }}
    namespace: {{ .Release.Namespace }}