apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tacoservice.fullname" . }}-frontend
  labels:
    {{- include "tacoservice.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "tacoservice.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tacoservice.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ include "tacoservice.fullname" . }}-frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 25m
              memory: 25Mi
          ports:
            - name: http
              containerPort: 80