apiVersion: v1
kind: Service
metadata:
  name: {{ include "tacoservice.fullname" . }}-frontend
  labels:
    {{- include "tacoservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "tacoservice.frontend.selectorLabels" . | nindent 4 }}
